### ISSUE TITLE
Rename "GitLab" link in header nav to "Source Code"

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#111]

**Comment by jsowers13** [comment]
I can work on this for you

**Comment by colinkiama** [comment]
Great!

**Comment by colinkiama** [comment]
The file to change is in `templates/macros/body.html`.

In that file, there's a macro called "header". You should see a list of links in there.

**Comment by rakshit087** [comment]
> I can work on this for you

Hey! Let me know if you feel stuck anywhere. Happy to help :))
