### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by rakshit087** [colinkiama/vala-www#122]
I am trying to serve site with ```zola serve```, however getting some errors.

* invalid type: string "2022-03-18", expected a TOML datetime for key `date` at line 3 column 8
This can be fixed by removing the quotes around datetime at ./vala-www/content/blog/vala-0.56.md
I will make a PR for it.

* Function call 'load_data' failed
```
Error: Failed to render section '/home/rakshit/Coding/vala-www/content/_index.md'
Reason: Failed to render 'index.html'
Reason: Function call 'load_data' failed
Reason: /assets/showcase-items.json doesn't exist
```

This is the error I got after fixing first one.

**Comment by colinkiama** [comment]
Which version of Zola are you using?

**Comment by colinkiama** [comment]
Also, what happens if you replace the first line in `templates/partials/showcase.html`  with:  
```
{% set showcase_data = load_data(path="assets/showcase-items.json", type="json") %}
````

**Comment by rakshit087** [comment]
> Which version of Zola are you using?

zola 0.12.2

Also, I fixed the second error by replacing the path with ```path="./assets/showcase-items.json"```. It is working but not sure if it's the right approach.

**Comment by rakshit087** [comment]
> Also, what happens if you replace the first line in `templates/partials/showcase.html` with:
> 
> ```
> {% set showcase_data = load_data(path="assets/showcase-items.json", type="json") %}
> ```

This is also working, will add it in PR #123

**Comment by colinkiama** [comment]
> zola 0.12.2
This is probably why the build issues are happening for you and not me. Can you install Zola 0.15.3 and also update the requirements in the README to require Zola  version 0.15.3 or higher?

**Comment by rakshit087** [comment]
> > zola 0.12.2
> 
> This is probably why the build issues are happening for you and not me. [Can you install Zola 0.15.3](https://github.com/getzola/zola/releases/tag/v0.15.3) and also update the requirements in the README to require Zola version 0.15.3 or higher?

Okay will do so.

**Comment by rakshit087** [comment]
Awesome it worked after updating zola. Closing the issue as well as the PR

**Comment by colinkiama** [comment]
Oh, you can reopen the PR to update the README

**Comment by colinkiama** [comment]
Actually never mind, I'll do that
