### ISSUE TITLE
Add editor recommendations, setup guides to tooling section

### ISSUE THREAD

**Issue by apachejuice** [colinkiama/vala-www#125]
I believe it would be helpful to have other language related tooling such as the preferred editors under the tooling section (Vim, VSCode, Gnome builder are what VLS supports) and perhaps setup guides accessible outside of the respositories for vala-specific tooling such as VLS (the repo has instruction on how to set it up on your editor) or even just link to them. It would be especially beginner-friendly i think.

**Comment by colinkiama** [comment]
@lw64 was this planned to be on the docs site?

**Comment by lw64** [comment]
> @lw64 was this planned to be in the docs site?

yes. That would be int the documentation under a tooling section.

**Comment by colinkiama** [comment]
Okay. The links in the Tooling section can go to the docs site instead.

We just need those pages in the docs site to be added first.

**Comment by lw64** [comment]
I added a section now, that can be linked to. Although only official tooling that is part of the Vala project should be documented there.

**Comment by colinkiama** [comment]
Some information on using meson would be great too!
