### ISSUE TITLE
Add theme color metadata

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#16]
Allows the website to influence the styling of a client's browser/system UI.

For more details, see the following:
https://css-tricks.com/safari-15-new-ui-theme-colors-and-a-css-tricks-cameo/
https://developer.apple.com/videos/play/wwdc2021/10029/

**Comment by colinkiama** [comment]
@Suzie97 what we were talking about earlier

**Comment by Suzie97** [comment]
> @Suzie97 what we were talking about earlier

https://gitlab.gnome.org/GNOME/epiphany/-/issues/1553

This discussion on implementing this on Epiphany.

**Comment by colinkiama** [comment]
I accidentally did work on this in the `main` branch. Oops 😅.

The good news is though, you can see the changes now on GitHub Pages.

Some screenshots on an iPhone 11:

![image](https://user-images.githubusercontent.com/16501024/166578560-1a86dc21-879d-40fd-8ee0-3494a429346b.png)

![image](https://user-images.githubusercontent.com/16501024/166578658-2d680858-70f1-4aaa-be67-024677d1fdfa.png)

![image](https://user-images.githubusercontent.com/16501024/166578709-6645ecb3-fa28-4d77-849f-70b1dba9becd.png)

**Comment by Suzie97** [comment]
<img width="1460" alt="Screenshot 2022-05-04 at 03 55 11" src="https://user-images.githubusercontent.com/68198116/166579971-2c1c564a-2cc3-4f34-96e0-6324e02e21f3.png">

Looks great on mac too

**Comment by colinkiama** [comment]
Wow that does look great. Hmm the background colour does need to be updated to be a solid colour though.

**Comment by nahuelwexd** [comment]
The gradient on the background should be vertical :eyes:

I remember making it vertical on the Penpot version of the design, dunno the Figma version

**Comment by colinkiama** [comment]
Oop i was just about to push as well 😂

**Comment by nahuelwexd** [comment]
ok wait, now that I saw the commit message, I need to clarify that the theme-color metadata tag is actually a thing Google introduced in 2014 for Android 5: https://developer.chrome.com/blog/support-for-theme-color-in-chrome-39-for-android/

... not an apple thing

**Comment by colinkiama** [comment]
I do have to say, the background gradient in the Figma version does seem dull compared to the one being used now. I think that the gradient should be updated in Figma.

**Comment by colinkiama** [comment]
> I do have to say, the background gradient in the Figma version does seem dull compared to the one being used now. I think that the gradient should be updated in Figma.

Let's continue this here: https://github.com/colinkiama/vala-www/discussions/10
