### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#21]
I'm not sure which license should be used in this case. Any suggestions?

**Comment by nahuelwexd** [comment]
I think CC BY-SA 4.0

**Comment by nahuelwexd** [comment]
@dar5hak @lw64 are contributors too, so they should agree with the license too

**Comment by lw64** [comment]
I am fine with that.

**Comment by dar5hak** [comment]
Yup, BY-SA sounds good.
