### ISSUE TITLE
Add menu styles for mobile

### ISSUE THREAD

**Issue by pervoj** [colinkiama/vala-www#23]
I am working on it right now.

**Comment by Suzie97** [comment]
@colinkiama was talking about not using hamburger menus, so I think we should have a discussion at first

**Comment by pervoj** [comment]
@colinkiama @Suzie97 So how do you plan style the menu for mobile?

**Comment by Suzie97** [comment]
> @colinkiama @Suzie97 So how do you plan style the menu for mobile?

![image](https://user-images.githubusercontent.com/68198116/166628602-522df653-263d-4b8d-9064-72dea7b7d66d.png)

Something like rust...

**Comment by colinkiama** [comment]
Well at first I didn't want a hamburger menu but now, I do think it would be nice to have one when JavaScript is enabled on mobile devices.

It would look a lot more organised and it would make the majority of the code example visible without scrolling.

**Comment by pervoj** [comment]
I'll finish it in the afternoon and you can then tell your opinion.
