### ISSUE TITLE
Use link colours with better contrast in the header and footer

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#25]

**Comment by dar5hak** [comment]
Okay, I did some testing in Firefox devtools, and there's no way of meeting AAA guidelines here without darkening the background gradient. With the current combination, there's [no combination](https://learnui.design/tools/accessible-color-generator.html) that meets AAA for small text.

**Comment by dar5hak** [comment]
Making the text white does make Firefox happy, but if we do that, we'll have to find an alternative way of displaying active links (which is a good idea anyway).

**Comment by nahuelwexd** [comment]
Darkening the background will make it somewhat less “eye-hurting” (to quote @lw64) I suppose.

**Comment by colinkiama** [comment]
White/very dark header and footer background with a light/dark shade for the body background? 🤔

**Comment by colinkiama** [comment]
From the [`aaa-contrast` branch](https://github.com/colinkiama/vala-www/tree/aaa-contrast):
![Screenshot from 2022-05-08 12-35-42](https://user-images.githubusercontent.com/16501024/167294377-b792b01e-3947-4190-946a-d2696c5ed58c.png)
![Screen Shot 2022-05-08 at 12 36 08](https://user-images.githubusercontent.com/16501024/167294381-16ea050e-58f4-4358-939f-55323aef658a.png)

All the links have AAA color contrast. (There is still some issues with the bypass block but that'll probably be fixed by the time you see this)
