### ISSUE TITLE
Change footer from a macro to a partial

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#27]
There's no data we need to pass into it so we should reference it with an `include` instead.

It should be in its own directory called `partials` under the `templates` directory.

**Useful Links**:
https://tera.netlify.app/docs/#include

**Comment by colinkiama** [comment]
@Marki2019

**Comment by Marki2019** [comment]
seems doable to a monke like me

**Comment by colinkiama** [comment]
Great! Feel free to ask any questions if you get stuck.
