### ISSUE TITLE
Use environment variables to decide which global stylesheet to use

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#28]
The way it is being done now isn't very flexible: https://github.com/colinkiama/vala-www/blob/main/templates/base.html#L10

Tera has a `get_env` function that helps with this: https://tera.netlify.app/docs/#get-env

**Comment by nahuelwexd** [comment]
I think this issue is no longer relevant, is it?

**Comment by colinkiama** [comment]
Yeah, it isn’t. Thanks.
