### ISSUE TITLE
Rocket icon needs special handling

### ISSUE THREAD

**Issue by nahuelwexd** [colinkiama/vala-www#42]
The rocket icon is a bit special. Its real center is not the one that we think it is, so as a result it looks misaligned 

This icon needs to have a bit negative margin so it can be visually centered.

**Comment by colinkiama** [comment]
In the [pull request that updates the home page](https://github.com/colinkiama/vala-www/pull/48) there are changes to the way the icons are used.

What do you think? Does it still need a negative margin? 

![image](https://user-images.githubusercontent.com/16501024/174774208-490f8b31-ba73-42fd-8d0e-500716c318c0.jpeg)

**Comment by nahuelwexd** [comment]
In that design, it is no longer noticeable whether it is misaligned, so no workaround would be necessary.

Feel free to close this issue as soon as the new design is merged.
