### ISSUE TITLE
Dark style support

### ISSUE THREAD

**Issue by dar5hak** [colinkiama/vala-www#5]
I am thinking of adding a dark style that responds to the user's OS-level preference.

Here is a concept; let me know what you think:

![image](https://user-images.githubusercontent.com/8205055/123919268-65c0de00-d9a2-11eb-8f13-8aa807ab3e90.png)

All colours are taken from [elementary Brand Palette](https://elementary.io/brand#color), which made sense, since the purple in the light style (#a56de2) was exactly Grape 500.

I would use Solarized Dark for the code, but it is not included in Prism. We can explore more styles.

**Comment by nahuelwexd** [comment]
The more I look at it, the more I like it xd It even makes me wonder if we should have a header with that background color even in the light theme

Also... Is the monospaced font different? :thinking: 

About solarized dark, there're some npm packages with that style for prism, so it shouldn't be a problem

**Comment by dar5hak** [comment]
Let me experiment with header background colours and see if something fits.

As for the font, every syntax highlighting style applies a different font stack, so it looks different in each. However, both Solarized Light and Tomorrow picked the same font (Menlo?) on this machine (macOS), so I went with it. Yet to check on Linux though.

**Comment by colinkiama** [comment]
Just to test the feature, I just swapped around the body's background and foreground for now: 
![image](https://user-images.githubusercontent.com/16501024/166129398-d824a25b-5906-4891-a388-6c4ca25744d3.png)

I'm having trouble making the code example's colours change based on the theme in production builds at the moment.

**Comment by Suzie97** [comment]
> Just to test the feature, I made simple changes to the body's background and foreground for now: 
> 
> ![image](https://user-images.githubusercontent.com/16501024/166129398-d824a25b-5906-4891-a388-6c4ca25744d3.png)
> 
> 
> 
> It's live on the github pages build now: https://colinkiama.github.io/vala-www/
> 
> 
> 
> I'm having trouble making the code example's colours change based on the theme in production builds at the moment. 
> 
> 
> 
> I really like the concept in the first post too. Maybe some inspiration for you @Suzie97 ?

Based on solely aesthetics, I like @dar5hak 's version more, but I think the darker background could actually make more sense in a dark mode setting.

**Comment by pervoj** [comment]
This issue is probably done and can be closed

**Comment by colinkiama** [comment]
I do apologise for not really engaging more with this when implementing the dark mode styles. Thankfully it worked out in the end :sweat_smile: .
