### ISSUE TITLE
Figure out a roadmap for inital launch

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#54]
Creating a `v1` project and adding issues to the project board may help with tracking progress.

**Comment by lw64** [comment]
What I think!:
Content and desing of the main page should be finished for a 1.0.
Blog and About can be added later.

**Comment by colinkiama** [comment]
I wouldn't leave those other pages out. It wouldn't take that long to get the design and content done for the main page.

It has only taken 2 weeks of commits to get to this point where we are now (and that's including the time where I switched to Zola, Next.js then back to Zola again)

Worst case scenario, we do a few tweaks to the about page and the blog.

**Comment by colinkiama** [comment]
Currently doing this using GitHub projects: https://github.com/users/colinkiama/projects/2

**Comment by nahuelwexd** [comment]
Why a personal project instead of a project here? :thinking:

**Comment by colinkiama** [comment]
The new GitHub projects are tied to your profile. It would be much easier if this work was being done under the [vala-lang organisation](https://github.com/vala-lang)
