### ISSUE TITLE
List language tooling somewhere on the website

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#55]

**Comment by nahuelwexd** [comment]
I don't think this should be explicitly on the website, I think it should be in the Getting Started in Vala's docs

**Comment by colinkiama** [comment]
Yea

**Comment by colinkiama** [comment]
Here's the issue for it in the docs repo: https://gitlab.gnome.org/lwildberg/vala-tutorial/-/issues/3

**Comment by colinkiama** [comment]
Now in the new docs website: https://docs.vala.dev/tooling/index.html
