### ISSUE TITLE
Better domain

### ISSUE THREAD

**Issue by pervoj** [colinkiama/vala-www#6]
It would be nice to move this website to better domain. Maybe write to the GNOME Foundation if they can change the DNS for the `vala-project.org` domain. Or register for example `vala.tk`.

**Comment by nahuelwexd** [comment]
@Prince781 had already bought `vala-lang.org`, the plan is to use that domain when the time comes to "release" the website.

About `vala-project.org`, I think we could ask Jürg to redirect the hits to `vala-lang.org`?

**Comment by Prince781** [comment]
Yup, we plan on using https://www.vala-lang.org

**Comment by colinkiama** [comment]
Hey, has there been any updates?

**Comment by nahuelwexd** [comment]
@colinkiama no updates. The plan on using vala-lang.org is still there, just that we need to get finish the website first, and then ask @Prince781 so that we can use the domain

**Comment by benwaffle** [comment]
@Prince781 I bought vala.dev, if you want to use that

**Comment by nahuelwexd** [comment]
ok wait, so now we have: `vala-project.org` (is the one being used right now, owned by Jürg), `vala-lang.org` (bought by @Prince781), and `vala.dev` (bought by @benwaffle)...

which one should we use?

**Comment by Prince781** [comment]
My opinion is that vala.dev should be used for tutorials and developer documentation (not just ValaDoc), while vala-lang.org should be the main website for the language (introduction, features, release notes, language showcase, and links to the other sites).

Or perhaps we could just make vala.dev redirect to vala-lang.org/learn

I don't want to have things fragmented. @benwaffle what do you think? Are there other *.dev sites to draw examples from?

**Comment by nahuelwexd** [comment]
There's go.dev and dart.dev that I know of

**Comment by pervoj** [comment]
I would prefer to have everything on one domain and subdomains and I personally like all three domains.

So I did a bit of research on which TLD is cheaper and I would go with `vala.dev`. It is also the shortest.

**Comment by Marki2019** [comment]
> We should only be using a single domain. And my vote is on vala.dev because it's shorter and easier to type. It's about $12/yr. Otherwise, it doesn't make that much of a difference

Vala.dev is good, im all for it.

**Comment by nahuelwexd** [comment]
Ok then… let's go for vala.dev after all?

**Comment by Prince781** [comment]
Alright, if we go with `vala.dev`, I'll just make `vala-lang.org` redirect to it.
