### ISSUE TITLE
Open Graph Metatags

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#61]
This would allow us to customise what is displayed in link previews.

I think that by default, there should be a default landscape image, that can be overwritten.

I created the `og_data` and `og_data_with_image` macros to help with this: https://github.com/colinkiama/vala-www/blob/dev/templates/macros/head.html

**References:**
https://ogp.me/

**Comment by pervoj** [comment]
What about some of these?

![vala-poster_Page 1](https://user-images.githubusercontent.com/71781857/172168807-4ed33089-71bf-4531-83ed-ef29f8b332f6.png)

![vala-poster_Page 2](https://user-images.githubusercontent.com/71781857/172168819-2ca00561-49ef-4dc9-b8c8-45256df2f30f.png)

**Comment by dar5hak** [comment]
The first one looks great. Just a V might be less familiar to people who don't regularly talk about Vala.

**Comment by nahuelwexd** [comment]
The V alone could be confused with the V programming language, I suppose.

I would like the images to be a bit more illuminated perhaps?

**Comment by pervoj** [comment]
> I would like the images to be a bit more illuminated perhaps?

I tried to enlarge the size of the circles and I think it looks better now.

![vala-poster_Page 3](https://user-images.githubusercontent.com/71781857/172434776-7624e079-34ef-469e-b354-af1d44fa732e.png)

**Comment by colinkiama** [comment]
I think that the colours used are too a bit too dark. Maybe consider using some of the brighter “grape” colours from [elementary colour palette](https://elementary.io/brand).

**Comment by colinkiama** [comment]
> > I would like the images to be a bit more illuminated perhaps?
> 
> I tried to enlarge the size of the circles and I think it looks better now.
> 
> ![vala-poster_Page 3](https://user-images.githubusercontent.com/71781857/172434776-7624e079-34ef-469e-b354-af1d44fa732e.png)

I think that the "Vala" text should be white or a brighter colour. The background colours were fine after all (sorry about that)

**Comment by colinkiama** [comment]
> > I would like the images to be a bit more illuminated perhaps?
> 
> I tried to enlarge the size of the circles and I think it looks better now.
> 
> ![vala-poster_Page 3](https://user-images.githubusercontent.com/71781857/172434776-7624e079-34ef-469e-b354-af1d44fa732e.png)

This is the best one so far imo :sweat_smile: 

I really appreciate how quick you are with these drafts

**Comment by pervoj** [comment]
It's just Inkscape, rectangles, circles and one Vala logo :)

**Comment by pervoj** [comment]
Btw. is the size fine? This is FullHD, 1920 x 1080 px. Isn't it too large?

**Comment by colinkiama** [comment]
Yes, a 1200x600px would be more suitable would be okay?

The ratio is on purpose by the way. It’s intentionally 2:1

**Comment by pervoj** [comment]
So the final version:

![vala-poster-final](https://user-images.githubusercontent.com/71781857/174046148-5d4f974e-108c-481f-b261-acd8a0485198.png)

**Comment by pervoj** [comment]
@Suzie97 Here it is:

![vala-poster](https://user-images.githubusercontent.com/71781857/174141829-1203e2cc-06b8-4a1b-a57e-5b2d7440e806.svg)

**Comment by pervoj** [comment]
This will maybe be better: https://oshi.at/YLqr

**Comment by Suzie97** [comment]
> Oh, I don't know if you'll be able to download it this way...

right click > download image saves it as an SVG :)

**Comment by pervoj** [comment]
Ok :)

**Comment by pervoj** [comment]
> So the final version:
> 
> ![vala-poster-final](https://user-images.githubusercontent.com/71781857/174046148-5d4f974e-108c-481f-b261-acd8a0485198.png)

I found out I forgot to change the logo color back. So here is the fixed variant:

![vala-poster_Page 7](https://user-images.githubusercontent.com/71781857/174145918-c43919b8-6664-4692-abe3-e65bc46e30e5.png)

**Comment by Suzie97** [comment]
## Adding shadows to the circles
![Artboard 4](https://user-images.githubusercontent.com/68198116/174151006-ec7e786a-160d-4fb6-9391-ae137857e687.png)

## Trying to use the elementary palette for some consistency
![Artboard 3](https://user-images.githubusercontent.com/68198116/174150982-804c6917-019e-4e03-974d-e114d32bf3d4.png)

## Windows 11 Wallpaper styles organic curves (but 2d)
![Artboard](https://user-images.githubusercontent.com/68198116/174151010-e8d367be-c969-436e-8202-fb850927bc0f.png)

Also, the curves go well with the cursive Vala logotype

## Same curves with the elementary colour palette

![Artboard 2](https://user-images.githubusercontent.com/68198116/174150972-9121af09-eee6-42b4-b82f-8f0e59e1c972.png)

**Comment by pervoj** [comment]
@Suzie97 Love it!

**Comment by Suzie97** [comment]
> @Suzie97 Love it!

which one do you prefer?

**Comment by pervoj** [comment]
> which one do you prefer?

The version with elementary's colors looks very nice. So does the first one, but more subtle. I really like what have you done with the curves. It's really hard to pick one because they all look good... So I think it's on Colin :)

**Comment by colinkiama** [comment]
Woooow 😳

**Comment by colinkiama** [comment]
I can’t decide between the regular circles with shadows and the regular organic curves 🤔

**Comment by dar5hak** [comment]
Curves!

**Comment by colinkiama** [comment]
I like the curves with the elementary palette the best!

**Comment by colinkiama** [comment]
I'm going to push through with it anyway. I expected a lot more backlash.

@Suzie97 can you send me the SVG file please? There could be some tweaks to do later.

**Comment by Suzie97** [comment]
> I'm going to push through with it anyway. I expected a lot more backlash.
> 
> @Suzie97 can you send me the SVG file please? There could be some tweaks to do later.

![Vala Background 1](https://user-images.githubusercontent.com/68198116/176128923-86b07d16-bd5c-48f8-8182-325fc960d5a3.svg)

**Comment by Suzie97** [comment]
I think it's a problem with the software used. I'll try to do this with Inkscape

**Comment by pervoj** [comment]
I think without the glow it looked better :)

**Comment by colinkiama** [comment]
> > I'm going to push through with it anyway. I expected a lot more backlash.
> > @Suzie97 can you send me the SVG file please? There could be some tweaks to do later.
> 
> ![Vala Background 1](https://user-images.githubusercontent.com/68198116/176128923-86b07d16-bd5c-48f8-8182-325fc960d5a3.svg)
> 
> Uhh, tt looks weird in this GitHub preview

Yeah it was better without the glowing text

**Comment by colinkiama** [comment]
Nvm, I can change that
