### ISSUE TITLE
Code example displays incorrectly when JavaScript is unavailable

### ISSUE THREAD

**Issue by colinkiama** [colinkiama/vala-www#81]
The code example relies on [prism.js](https://prismjs.com/) for formatting and highlighting. When it's not available, here's what the home page looks like:
![Screen Shot 2022-06-21 at 21 27 39](https://user-images.githubusercontent.com/16501024/174892081-ed949b61-285b-4960-8bc8-2de1d82bd6f4.png)

If a fix can't be found, the code example should be hidden and the global header should have the "diagonal slice" effect when JavaScript is off.

**Comment by nahuelwexd** [comment]
Uh, this is too far from what I expected. In the previous version of the site, when JavaScript was not available, the code simply lost its highlighting, it didn't break the layout.

**Comment by pervoj** [comment]
We can make the highlighting done with Zola. I've already did something similar on my website: https://github.com/pervoj/website/tree/main/syntaxes

**Comment by colinkiama** [comment]
> We can make the highlighting done with Zola. I've already did something similar on my website: https://github.com/pervoj/website/tree/main/syntaxes
> 
> It needs to add a line to Zola config: https://github.com/pervoj/website/blob/main/config.toml#L15

Is there a page on your website there is a Vala code block?

**Comment by pervoj** [comment]
I found out one thing: Zola supports highlighting only in .md files.

**Comment by colinkiama** [comment]
If loaded markdown content was passed through the [markdown filter](https://www.getzola.org/documentation/templates/overview/#markdown) would the highlighting still work?

It also looks from the [syntax_highlighting docs](https://www.getzola.org/documentation/content/syntax-highlighting/#inline-vs-classed-highlighting), `highlight_themes_css` will allow us to continue using a separate light and dark theme for syntax highlighting.
